services:
    system-web:
        container_name: system-web
        image: nginx:alpine
        ports:
            - "9090 :80"
        volumes:
            - ./:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - system-app
        networks:
            - system-network

    system-app:
        container_name: system-app
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        depends_on:
            - postgres
        volumes:
            - ./:/var/www
        networks:
            - system-network

    postgres:
        image: postgres
        container_name: system-postgres
        restart: always
        expose:
            - 5432
        ports:
            - "23456:5432"
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - system_postgres_data:/var/lib/postgresql/data
        networks:
            - system-network

    system-pgadmin:
        image: dpage/pgadmin4
        container_name: system-pgadmin
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        ports:
            - "9001:80"
        networks:
            - system-network

    system-node:
        image: node:20
        container_name: system-node
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - system-network
        command: bash -c "npm install && npm run build && npm run dev"

networks:
    system-network:
        driver: bridge

volumes:
    system_postgres_data:
